Repository wecode-bootcamp-korea/26-2nd-WESELL-frontend, pull requests merged in 2021-11, with the labels that each got.

#2 [26기 옥원철] Modified: 리뷰 반영 - 컴포넌트명, 변수명 변경 등 리팩토링
  src/components/AboutCorp/AboutCorp.js
  src/components/AboutCorp/CorpInfo.js
  src/components/AboutCorp/CorpInfoLinks.js
  src/components/CustomerService/CustomerCenter.js
  src/components/CustomerService/CustomerService.js
  src/components/CustomerService/CustomerServiceList.js
  src/components/Footer.js
Labels: Status: 리뷰 요청

#1 [26기 옥원철] Modified: 리뷰 반영 - 컴포넌트명, 변수명 변경 등 리팩토링
  package-lock.json
  public/data/delete.js
  public/images/delete.js
  public/index.html
  src/components/Nav.js
  src/pages/LoginRegister/Delete.js
Labels: Status: 리뷰 요청

#9 [26기 옥원철] [Main] Layout 수정 완료
  public/data/ProductCardList.json
  public/data/ProductCardMock.js
  public/images/img1.jpg
  public/images/img2.jpg
  public/images/img3.jpg
  public/images/img4.jpg
  public/images/img5.jpg
  public/images/img6.jpg
  src/components/ProductCard.js
  src/components/ProductCard/ProductCardList.js
  src/components/ProductCard/ProductCardTitle.js
  src/components/ProductCard/ProductCardWrap.js
  src/components/ProductCard/Products.js
  src/pages/Main/Advertisement/Advertisement.js
  src/pages/Main/Advertisement/AdvertisementList.js
  src/pages/Main/Main.js
  src/pages/Main/MainSlider/MainSlider.js
  src/pages/Main/MainSlider/SlideBtn.js
  src/pages/Main/MainSlider/SlideData.js
  src/pages/Main/MainSlider/icons/left-arrow.svg
  src/pages/Main/MainSlider/icons/right-arrow.svg
Labels: Status: Accepted

#4 [26기 전지완] Detail Product Page Layout
  package-lock.json
  package.json
  src/Router.js
  src/pages/Order/Order.js
  src/pages/ProductDetail/ColumnTop.js
  src/pages/ProductDetail/MarketPrice.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductInfo.js
  src/pages/ProductDetail/components/Modal.js
Labels: Status: Conflict 해결 요청

#10 [26기 옥원철 ][Nav] Add: SearchBar 레이아웃 추가 및 버튼별 링크 구현, 충돌 해결
  public/data/ProductCardList.json
  src/Router.js
  src/components/Nav/BrandList.js
  src/components/Nav/Nav.js
  src/components/Nav/RecentSearch.js
  src/components/Nav/SearchBar.js
  src/components/Nav/SearchByBrand.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#13 [26기 안재우]Feature/shop add function
  package-lock.json
  public/data/RightContainer.json
  public/data/ShopCategoryDate.json
  src/Router.js
  src/components/ProductCard/ProductCard.js
  src/pages/Main/MainSlider/MainSlider.js
  src/pages/ProductDetail/MarketPrice.js
  src/pages/Shop/FliterAside/FilterOptionContainer.js
  src/pages/Shop/FliterAside/FliterOption/Option.js
  src/pages/Shop/FliterAside/FliterOption/SubOption.js
  src/pages/Shop/LeftSide/LeftButton/SubCategoryList.js
  src/pages/Shop/LeftSide/LeftCategoryContainer.js
  src/pages/Shop/ProductList/ProductList.js
  src/pages/Shop/ProductList/SortingBox/SortingBox.js
  src/pages/Shop/RightSide/RightContianer.js
  src/pages/Shop/Shop.js
  src/pages/Shop/Topside/TopsideContainer.js
Labels: Status: 리뷰 요청

#18 [26기 안재우]modify : topside 삭제
  src/Router.js
  src/components/ProductCard/ProductCard.js
  src/pages/Shop/ProductList/ProductList.js
  src/pages/Shop/Shop.js
Labels: Status: 리뷰 요청

#21 [26기 옥원철] Modified: [Main] 리뷰 반영 및 충돌해결
  public/images/Image1.png
  public/images/Image2.png
  public/images/Image3.png
  public/images/Image4.png
  public/images/Image5.png
  public/images/Image6.png
  public/images/img1.jpg
  public/images/img2.jpg
  public/images/img3.jpg
  public/images/img4.jpg
  public/images/img5.jpg
  public/images/img6.jpg
  src/Router.js
  src/components/ProductCard/ProductCardMain.js
  src/components/ProductCard/ProductCardWrap.js
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/MainSlider/MainSlider.js
  src/pages/Main/MainSlider/SlideData.js
  src/pages/Shop/Shop.js
Labels: Status: 리뷰 요청

#12 [26기 강지원]: style layout 구현, 기능 구현 시작
  package-lock.json
  package.json
  public/data/styleComment.json
  public/data/styleData.json
  public/images/신발사진_001.jpg
  public/images/신발사진_002.jpg
  src/Router.js
  src/pages/Main/MainSlider/MainSlider.js
  src/pages/StyleTrend/CommentModal.js
  src/pages/StyleTrend/StyleLayout.js
  src/pages/StyleTrend/StyleTrend.js
Labels: Status: 리뷰 요청

#24 [26기 옥원철] Add: [Order] 구매 및 판매 POST, DELETE 요청 구현
  public/data/OrderMockData.json
  public/images/DefaultImage.png
  src/Router.js
  src/components/KakaoLogin/Oauth.js
  src/components/KakaoLogin/Redirect.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/Main/MainSlider/MainSlider.js
  src/pages/Main/MainSlider/slidesData.js
  src/pages/Order/BidDeadline.js
  src/pages/Order/Order.js
  src/pages/Order/OrderDetail.js
  src/pages/Order/OrderHow.js
  src/pages/Order/ShoesInfo.js
  src/pages/Order/SubmitPrice.js
  src/pages/Order/orderType.js
  src/utils/queryStringBody.js
Labels: Status: 리뷰 요청

#25 [26기 강지원] image data, comment data 서버 전송 기능 완료
  src/components/KakaoLogin/Oauth.js
  src/components/UseSearchParams.js
  src/pages/StyleTrend/CommentModal.js
  src/pages/StyleTrend/StyleLayout.js
Labels: Status: 리뷰 요청

#26 [26기 전지완] 드디어 종택님이 멘트 주신대로 했습니다
  src/Router.js
  src/config.js
  src/pages/ProductDetail/Bargain.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/Shop/FliterAside/FilterOptionContainer.js
  src/pages/Shop/ProductList/ProductList.js
Labels: Status: 리뷰 요청

#29 login 기능 수정
  src/components/KakaoLogin/Redirect.js
  src/components/Nav/Nav.js
  src/pages/Order/SubmitPrice.js
  src/pages/StyleTrend/CommentModal.js
Labels: Status: 리뷰 요청
